# Generated by Django 5.0.2 on 2024-09-07 13:01

from django.db import migrations
from django.db import models

import trainer_backend.core.file.utils


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_add_thematic_speech_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='question_number',
            field=models.PositiveIntegerField(null=True, verbose_name='Номер вопроса'),
        ),
        migrations.AddField(
            model_name='taskanswer',
            name='task_number',
            field=models.PositiveIntegerField(null=True, verbose_name='Номер задания'),
        ),
    ]
