# Generated by Django 5.0.2 on 2024-09-19 23:15

from django.db import migrations
from django.db import models

import trainer_backend.core.file.utils


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_questionanswer_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_archive',
            field=models.FileField(blank=True, null=True, upload_to=trainer_backend.core.file.utils.upload_hash_file, verbose_name='Архив ответа'),
        )
    ]
