# Generated by Django 5.0.2 on 2024-11-16 16:29

from django.db import migrations
from django.db import models

import trainer_backend.trainer.enums


class Migration(migrations.Migration):
    dependencies = [
        ('trainer', '0003_add_thematic_speech_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='processed',
        ),
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.SmallIntegerField(choices=[(
                                                    trainer_backend.trainer.enums.AnswerStatus[
                                                        'UNPROCESSED'],
                                                    'Необработан'), (
                                                    trainer_backend.trainer.enums.AnswerStatus[
                                                        'AUDIO_PROCESSED'],
                                                    'Аудио данные обработаны')],
                                           default=1),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='audio',
            field=models.FileField(upload_to='answer_raw/',
                                   verbose_name='Ответ на вопрос'),
        ),
        migrations.AlterField(
            model_name='taskanswer',
            name='audio',
            field=models.FileField(blank=True, null=True,
                                   upload_to='answer_raw/',
                                   verbose_name='Ответ на задание'),
        ),
    ]
