name: Build and push images

on:
  push:
    branches:
      - master
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2

    - name: Determine tag
      id: tag
      run: |
        if [[ $GITHUB_REF == refs/heads/master ]]; then
          echo "::set-output name=tag::latest"
        elif [[ $GITHUB_REF == refs/heads/develop ]]; then
          echo "::set-output name=tag::develop"
        fi

    - name: Build and push web container
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/web/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/trainer_web:${{ steps.tag.outputs.tag }}
